### ISSUE TITLE
Pre-trained model release as promised?

### ISSUE THREAD

**Issue by jakubLangr** [hufu6371/GcGAN#3]
Hi @hufu6371 , thank you so much for this fantastic work. 

I finally had the chance to see your team's great presentation from CVPR. 

But in the README you mention that you will be releasing the pretrained models soon. I could not find them, so I was wondering what the timeline is. 

Thanks a lot!

**Comment by hufu6371** [comment]
Hi,

Thanks for your reminder.

We have now provided the download links in the github.

Please see the readme for details.

Best regards,
Huan


________________________________

**Comment by jakubLangr** [comment]
Hi @hufu6371 ,

thank you so much for your timely response. I tried running this on the dataset provided using one of the pretrained models using the `test_gcgan.sh` command. Unfortunately, that results in the following error:

```
initialization method [xavier]
/usr/local/lib/python3.6/dist-packages/torchvision/transforms/transforms.py:220: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
/content/drive/My Drive/ml_work/GcGAN/models/networks.py:29: UserWarning: nn.init.xavier_normal is now deprecated in favor of nn.init.xavier_normal_.
  init.xavier_normal(m.weight.data, gain=0.02)
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    model = create_model(opt)
  File "/content/drive/My Drive/ml_work/GcGAN/models/models.py", line 47, in create_model
    model.initialize(opt)
  File "/content/drive/My Drive/ml_work/GcGAN/models/gc_gan_share_model.py", line 43, in initialize
    self.load_network(self.netG_AB, 'G_AB', which_epoch)
  File "/content/drive/My Drive/ml_work/GcGAN/models/base_model.py", line 53, in load_network
    network.load_state_dict(torch.load(save_path))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResnetGenerator:
	Missing key(s) in state_dict: "model.16.weight", "model.16.bias", "model.23.weight", "model.23.bias". 
	Unexpected key(s) in state_dict: "model.26.weight", "model.26.bias", "model.16.conv_block.1.weight", "model.16.conv_block.1.bias", "model.16.conv_block.5.weight", "model.16.conv_block.5.bias", "model.17.conv_block.1.weight", "model.17.conv_block.1.bias", "model.17.conv_block.5.weight", "model.17.conv_block.5.bias", "model.18.conv_block.1.weight", "model.18.conv_block.1.bias", "model.18.conv_block.5.weight", "model.18.conv_block.5.bias", "model.22.weight", "model.22.bias". 
	size mismatch for model.19.weight: copying a param with shape torch.Size([256, 128, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 64, 3, 3]).
	size mismatch for model.19.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([64]).
```
Any further modifications needed? What detail would help? I am on Pytorch `1.3.1`. 

Let me know! :)
